#!/usr/local/bin/perl

use LWP::UserAgent;
use Getopt::Long;
use strict;
use vars qw($opt_proxy $opt_debug);
use Data::Dumper qw(Dumper);

GetOptions(
	   'd' => \$opt_debug,
	   'p:s' => \$opt_proxy,
	   'proxy:s' => \$opt_proxy
	   );

if($opt_debug) {
    eval "use LWP::Debug qw(+);";
}

# PROXY SUPPORT
$ENV{HTTPS_PROXY} = $opt_proxy;
$ENV{HTTPS_DEBUG} = $opt_debug;
	 
my $url = shift || 'https://www.nodeworks.com';
my $ua = new LWP::UserAgent;
my $req = new HTTP::Request('HEAD', $url);
my $res = $ua->request($req);

print Dumper($res);
